import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Navbar from "@/components/shared/Navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${geistSans.variable} antialiased bg-slate-50/50`}>
        <Providers>
          <div className="flex min-h-screen flex-col">
            <Navbar /> {/* Letakkan di sini */}
            <main className="flex-1">
              {children}
            </main>
            <Toaster position="top-center" richColors /> {/* Tambahkan di sini */}
            <footer className="border-t py-6 text-center text-sm text-muted-foreground bg-white">
              © {new Date().getFullYear()} JualMobilKu - Solusi Jual Mobil Cepat
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
